local Server = {
    ["Doors👁"] = "https://raw.githubusercontent.com/Potato5466794/Nolsaken/refs/heads/main/Load/HAX.luau",
    ["Forsaken[🔥]"] = "https://raw.githubusercontent.com/Potato5466794/Nolsaken/refs/heads/main/Load/NOLSAKEN.luau",

}-- ["Server Name"] = "Server Url",


local Other = {
    ["Nothing"] = "https://raw.githubusercontent.com/EdeoLex-43/Main/refs/heads/Script/%E7%BD%91%E6%98%93%E4%BA%91.lua",
} -- ["Server Name"] = "Server Url",
return Server, Other
